[project]
name = "ea-quantum-state-preparation"
version = "0.1.0"
requires-python = ">=3.10"

[tool.pylsp-mypy]
enabled = false

[tool.setuptools]
py-modules = ["qext"]

[tool.flake8]
ignore = ["E501", "W292"]
max-line-length = 120
exclude = [".venv", "__pycache__", "docs", "build"]
